url: https://shipfaster.me
baseurl: /
source: src

# Site settings
title: shipfaster.me
email: david@shipfaster.me
# The description will appear in your document head meta (for Google search results) and in your feed.xml site description.
description: "Automation Engineer living in Brooklyn."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 5a86c3
  secondary: 222  
  secondary-dark: 333

# Team names, titles and social links
personal:
  name: David Neudorfer
  pic: 1
  position: Automation Engineer
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
  social:
    - title: github
      url: http://www.github.com/davidneudorfer
    - title: linkedin
      url: http://www.linkedin.com/in/davidneudorfer
    - title: stack-overflow
      url: http://stackoverflow.com/users/1039166/david-neudorfer

# Postal address (add as many lines as necessary)
address:
  - line: Williamsburg, Brooklyn, NY

# Build settings
markdown: kramdown
permalink: pretty